[profile.release]
debug = true
lto = false # TODO: this can be changed?
strip = true

[workspace]
members = [
    #"kernel",

    "dev/image",

    #"lib/aarch64",
    #"lib/allocator",
    #"lib/fat32",
    "lib/formatted",
    "lib/formatted/formatted_derive",
    #"lib/persistent",
    #"lib/kernel_api",
    #"lib/pi",
    "lib/shim",
    #"lib/volatile",

    #"user",
]