[profile.release]
debug = true
lto = false
strip = true

[workspace]
members = [
    "kernel",

    "lib/aarch64",
    "lib/allocator",
    "lib/fat32",
    "lib/filesystem",
    "lib/jlib",
    "lib/kernel_api",
    "lib/pi",
    "lib/shim",
    "lib/volatile",
    "lib/xmodem",

    "user",
]