cargo-features = ["per-package-target"]

[package]
name = "image"
version = "0.1.0"
edition = "2021"
forced-target = "x86_64-apple-darwin"

[dependencies]
clap = { version = "4", features = ["derive"] }